version: '3'

services:
  postgres:
    container_name: "cinemabot_postgres"
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cinemabot_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-cinemabot_db}

  redis:
    container_name: "cinemabot_redis"
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT-6379}:6379
